import { fallbackContent } from './fallback'
import type { AdCycleZone, Content, ProjectItem, ServiceItem, SocialLink } from './types'

/**
 * Generated by `scripts/sync-content.mjs` from Sanity at build time. The file is
 * gitignored, so it is absent on a fresh clone / when no Sanity project is
 * configured — `import.meta.glob` then resolves to an empty object and the
 * committed fallback is used instead.
 */
const generated = import.meta.glob<{ default: Content }>('./content.json', { eager: true })
const generatedContent = generated['./content.json']?.default

/** Use the CMS list when it has entries, otherwise keep the committed fallback. */
function selectList<T>(cmsList: T[] | undefined, fallbackList: T[]): T[] {
  return Array.isArray(cmsList) && cmsList.length > 0 ? cmsList : fallbackList
}

/**
 * Merge Sanity content over the fallback *per section / per field*, so a
 * half-populated dataset renders the best available mix instead of reverting
 * the whole site to hardcoded content. Only once a section has content in the
 * CMS does it replace the fallback for that section.
 */
export const content: Content = generatedContent
  ? {
      siteSettings: {
        contactEmail:
          generatedContent.siteSettings?.contactEmail || fallbackContent.siteSettings.contactEmail,
        founderEmail:
          generatedContent.siteSettings?.founderEmail || fallbackContent.siteSettings.founderEmail,
        socials: selectList<SocialLink>(
          generatedContent.siteSettings?.socials,
          fallbackContent.siteSettings.socials,
        ),
        formFormatOptions: selectList<string>(
          generatedContent.siteSettings?.formFormatOptions,
          fallbackContent.siteSettings.formFormatOptions,
        ),
        formCityOptions: selectList<string>(
          generatedContent.siteSettings?.formCityOptions,
          fallbackContent.siteSettings.formCityOptions,
        ),
      },
      services: selectList<ServiceItem>(generatedContent.services, fallbackContent.services),
      projects: selectList<ProjectItem>(generatedContent.projects, fallbackContent.projects),
      adCycleZones: selectList<AdCycleZone>(
        generatedContent.adCycleZones,
        fallbackContent.adCycleZones,
      ),
    }
  : fallbackContent

export type {
  AdCycleZone,
  Content,
  ProjectItem,
  ServiceItem,
  SiteSettings,
  SocialLink,
} from './types'